package com.bt.shopguide.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Banner implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANNER.id
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANNER.type
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANNER.url
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANNER.alt
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    private String alt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANNER.target
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANNER.seq
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANNER.status
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANNER.start_time
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANNER.end_time
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANNER.create_time
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANNER.id
     *
     * @return the value of BANNER.id
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANNER.id
     *
     * @param id the value for BANNER.id
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANNER.type
     *
     * @return the value of BANNER.type
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANNER.type
     *
     * @param type the value for BANNER.type
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANNER.url
     *
     * @return the value of BANNER.url
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANNER.url
     *
     * @param url the value for BANNER.url
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANNER.alt
     *
     * @return the value of BANNER.alt
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public String getAlt() {
        return alt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANNER.alt
     *
     * @param alt the value for BANNER.alt
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public void setAlt(String alt) {
        this.alt = alt == null ? null : alt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANNER.target
     *
     * @return the value of BANNER.target
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANNER.target
     *
     * @param target the value for BANNER.target
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANNER.seq
     *
     * @return the value of BANNER.seq
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANNER.seq
     *
     * @param seq the value for BANNER.seq
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANNER.status
     *
     * @return the value of BANNER.status
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANNER.status
     *
     * @param status the value for BANNER.status
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANNER.start_time
     *
     * @return the value of BANNER.start_time
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANNER.start_time
     *
     * @param startTime the value for BANNER.start_time
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANNER.end_time
     *
     * @return the value of BANNER.end_time
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANNER.end_time
     *
     * @param endTime the value for BANNER.end_time
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANNER.create_time
     *
     * @return the value of BANNER.create_time
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANNER.create_time
     *
     * @param createTime the value for BANNER.create_time
     *
     * @mbggenerated Tue Dec 19 10:08:25 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}